services:
  app:
    container_name: faicord
    image: faicord-build
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - gh_token
    secrets:
      - gh_token
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/faicord 
    stdin_open: true
    tty: true
    command: bash
secrets:
  gh_token:
    file: token/github_token.txt