services:
  app:
    container_name: faicord
    image: faicord:latest
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/faicord 
      - /data/uploaded_files/audio:/faicord/dataset/audio
      - /data/uploaded_files/diar_results:/faicord/dataset/rttm 
      - /data/uploaded_files/stt_results/:/faicord/dataset/stt
      - /data/uploaded_files/summary_results/:/faicord/dataset/summary
    ports:
      - "9050:9050"
    stdin_open: true
    tty: true
    command: uvicorn web_url:app --host 0.0.0.0 --port 9050 --log-level info
    networks:
      - faicord-net
networks:
  faicord-net:
    external: true
